#pragma once

#include <uxr/client/client.h>

#include <array>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <tuple>
#include <type_traits>

#include "sensor_msgs/msg/Imu.h"

constexpr uxrQoS_t DEFAULT_QOS = {
    UXR_DURABILITY_VOLATILE,
    UXR_RELIABILITY_BEST_EFFORT,
    UXR_HISTORY_KEEP_LAST,
    1,
};

constexpr uint16_t DEFAULT_PUBLISHER_KEY = 0x01;
constexpr uint16_t DEFAULT_SUBSCRIBER_KEY = 0x01;

enum class TopicId : uint16_t;

// DDSClient stores topic operations generically so the runtime code does not
// need to know every generated message type at compile sites outside topics.h.
using TopicSizeFunc = uint32_t (*)(const void* msg, uint32_t size);
using TopicSerializeFunc = bool (*)(ucdrBuffer* writer, const void* msg);
using TopicDeserializeFunc = bool (*)(ucdrBuffer* reader, void* msg);

// Adapts the typed functions generated by microxrceddsgen to the generic
// function pointer shape stored in Topic. New topics should use make_topic()
// instead of hand-writing wrappers for size/serialize/deserialize.
template <
    typename MessageT,
    uint32_t (*SizeOfTopic)(const MessageT* msg, uint32_t size),
    bool (*SerializeTopic)(ucdrBuffer* writer, const MessageT* msg),
    bool (*DeserializeTopic)(ucdrBuffer* reader, MessageT* msg)>
struct TopicTypeAdapter {
  static uint32_t size_of_topic(const void* msg, const uint32_t size)
  {
    return SizeOfTopic(static_cast<const MessageT*>(msg), size);
  }

  static bool serialize_topic(ucdrBuffer* writer, const void* msg)
  {
    return SerializeTopic(writer, static_cast<const MessageT*>(msg));
  }

  static bool deserialize_topic(ucdrBuffer* reader, void* msg)
  {
    return DeserializeTopic(reader, static_cast<MessageT*>(msg));
  }
};

/// User-facing topic config. Object IDs come from the explicit TopicId value
/// supplied next to each entry in topics[].
struct Topic {
  enum class Direction : bool {
    WRITER,
    READER,
  };

  const TopicId id;
  const char* name;
  const char* topic_name;
  const char* type_name;
  const uxrQoS_t qos;
  const Direction dir;

  // These type hooks must match type_name. Use make_topic() so the typed
  // generated functions are adapted to DDSClient's generic void* path.
  const std::size_t message_size;
  const TopicSizeFunc size_of_topic;
  const TopicSerializeFunc serialize_topic;
  const TopicDeserializeFunc deserialize_topic;
};

template <typename MsgType>
struct SpecificTopic : Topic {
  using Message = MsgType;

  constexpr SpecificTopic(
      const TopicId id,
      const char* name,
      const char* topic_name,
      const char* type_name,
      const uxrQoS_t qos,
      const Direction dir,
      const std::size_t message_size,
      const TopicSizeFunc size_of_topic,
      const TopicSerializeFunc serialize_topic,
      const TopicDeserializeFunc deserialize_topic
  )
      : Topic{id,  name,         topic_name,    type_name,       qos,
              dir, message_size, size_of_topic, serialize_topic, deserialize_topic}
  {
  }
};

// Adapts the typed functions generated by microxrceddsgen to the generic
// function pointer shape stored in Topic. New topics should use make_topic()
// instead of hand-writing wrappers for size/serialize/deserialize.
template <
    typename MessageT,
    uint32_t (*SizeOfTopic)(const MessageT* msg, uint32_t size),
    bool (*SerializeTopic)(ucdrBuffer* writer, const MessageT* msg),
    bool (*DeserializeTopic)(ucdrBuffer* reader, MessageT* msg)>
constexpr SpecificTopic<MessageT> make_topic(
    const TopicId id,
    const char* name,
    const char* topic_name,
    const char* type_name,
    const Topic::Direction dir,
    const uxrQoS_t qos = DEFAULT_QOS
)
{
  using Adapter = TopicTypeAdapter<MessageT, SizeOfTopic, SerializeTopic, DeserializeTopic>;
  return {
      id,
      name,
      topic_name,
      type_name,
      qos,
      dir,
      sizeof(MessageT),
      Adapter::size_of_topic,
      Adapter::serialize_topic,
      Adapter::deserialize_topic,
  };
}

// User-declared XRCE object keys for each entry in topics[].
// 0-based indexing to match with index in TOPICS
enum class TopicId : uint16_t {
  IMU_WRITER = 0x00,
  IMU_READER,
};

constexpr uint16_t to_underlying(TopicId topic_id)
{
  return static_cast<uint16_t>(topic_id);
}

// This is the only list users should normally edit when adding DDS topics.
// The generated functions passed to make_topic() must match the DDS type_name.
constexpr auto TYPED_TOPICS = std::tuple{
    make_topic<
        sensor_msgs_msg_Imu,
        sensor_msgs_msg_Imu_size_of_topic,
        sensor_msgs_msg_Imu_serialize_topic,
        sensor_msgs_msg_Imu_deserialize_topic>(
        TopicId::IMU_WRITER,
        "IMU Writer",
        "rt/imu",
        "sensor_msgs::msg::dds_::Imu_",
        Topic::Direction::WRITER
    ),
    make_topic<
        sensor_msgs_msg_Imu,
        sensor_msgs_msg_Imu_size_of_topic,
        sensor_msgs_msg_Imu_serialize_topic,
        sensor_msgs_msg_Imu_deserialize_topic>(
        TopicId::IMU_READER,
        "IMU Reader",
        "rt/imu",
        "sensor_msgs::msg::dds_::Imu_",
        Topic::Direction::READER
    ),
};

// Generates our nice TOPICS array from the tuple array
template <typename... TopicTs>
constexpr auto make_topic_array(const std::tuple<TopicTs...>& topics)
{
  return std::apply(
      [](const auto&... topic) { return std::array<Topic, sizeof...(TopicTs)>{static_cast<const Topic&>(topic)...}; },
      topics
  );
}

constexpr auto TOPICS = make_topic_array(TYPED_TOPICS);
constexpr std::size_t TOPIC_COUNT = TOPICS.size();

template <TopicId Id>
struct TopicMsg {
  static constexpr std::size_t index = to_underlying(Id);

  using TopicType = std::tuple_element_t<index, decltype(TYPED_TOPICS)>;
  using Message = typename std::remove_cv_t<TopicType>::Message;
};

/// Checks if TOPICS array if defined correctly. If topics are defined out-of-order
/// in according withATopicId, the static_assert will fail at compile time.
constexpr bool topic_ids_match_indices()
{
  for (std::size_t i = 0; i < TOPIC_COUNT; ++i) {
    if (static_cast<std::size_t>(TOPICS[i].id) != i) {
      return false;
    }
  }
  return true;
}

static_assert(topic_ids_match_indices(), "topics[] entries must match their zero-based TopicId indices");


/// Returns the Topic associated with the TopicId
inline const Topic* get_topic(const TopicId topic_id)
{
  const uint16_t index = to_underlying(topic_id);
  assert(index < TOPIC_COUNT && "Given topic_id does not exist in TOPICS array");
  return index < TOPIC_COUNT ? &TOPICS[index] : nullptr;
}

// Reader callbacks deserialize into a stack buffer sized for the largest
// configured message type. The callback must copy data it wants to keep.
constexpr std::size_t max_topic_message_size()
{
  std::size_t max_size = 0;
  for (const Topic& topic : TOPICS) {
    if (topic.message_size > max_size) {
      max_size = topic.message_size;
    }
  }
  return max_size;
}

// Counts are used to size the create-request/status arrays at compile time.
constexpr std::size_t datawriter_count()
{
  std::size_t count = 0;
  for (const Topic& topic : TOPICS) {
    if (topic.dir == Topic::Direction::WRITER) {
      ++count;
    }
  }
  return count;
}

constexpr std::size_t datareader_count()
{
  std::size_t count = 0;
  for (const Topic& topic : TOPICS) {
    if (topic.dir == Topic::Direction::READER) {
      ++count;
    }
  }
  return count;
}

// Object type keeps Topic/DataWriter/DataReader IDs separate even when they
// reuse the same user-declared numeric key.
constexpr uint16_t object_key(const std::size_t topic_index)
{
  return static_cast<uint16_t>(TOPICS[topic_index].id);
}

inline uxrObjectId topic_id(const std::size_t topic_index)
{
  return uxr_object_id(object_key(topic_index), UXR_TOPIC_ID);
}

inline uxrObjectId datawriter_id(const std::size_t topic_index)
{
  return uxr_object_id(object_key(topic_index), UXR_DATAWRITER_ID);
}

inline uxrObjectId datareader_id(const std::size_t topic_index)
{
  return uxr_object_id(object_key(topic_index), UXR_DATAREADER_ID);
}
