#pragma once

#include <uxr/client/client.h>

#include <cstddef>
#include <cstdint>

#include "sensor_msgs/msg/Imu.h"

constexpr uxrQoS_t DEFAULT_QOS = {
  UXR_DURABILITY_VOLATILE,
  UXR_RELIABILITY_BEST_EFFORT,
  UXR_HISTORY_KEEP_LAST,
  1,
};

constexpr uint16_t DEFAULT_PUBLISHER_KEY = 0x01;
constexpr uint16_t DEFAULT_SUBSCRIBER_KEY = 0x01;

// DDSClient stores topic operations generically so the runtime code does not
// need to know every generated message type at compile sites outside topics.h.
using TopicSizeFunc = uint32_t (*)(const void* msg, uint32_t size);
using TopicSerializeFunc = bool (*)(ucdrBuffer* writer, const void* msg);
using TopicDeserializeFunc = bool (*)(ucdrBuffer* reader, void* msg);

// Adapts the typed functions generated by microxrceddsgen to the generic
// function pointer shape stored in Topic. New topics should use make_topic()
// instead of hand-writing wrappers for size/serialize/deserialize.
template <
    typename MessageT,
    uint32_t (*SizeOfTopic)(const MessageT* msg, uint32_t size),
    bool (*SerializeTopic)(ucdrBuffer* writer, const MessageT* msg),
    bool (*DeserializeTopic)(ucdrBuffer* reader, MessageT* msg)>
struct TopicTypeAdapter {
  static uint32_t size_of_topic(const void* msg, const uint32_t size)
  {
    return SizeOfTopic(static_cast<const MessageT*>(msg), size);
  }

  static bool serialize_topic(ucdrBuffer* writer, const void* msg)
  {
    return SerializeTopic(writer, static_cast<const MessageT*>(msg));
  }

  static bool deserialize_topic(ucdrBuffer* reader, void* msg)
  {
    return DeserializeTopic(reader, static_cast<MessageT*>(msg));
  }
};

/// User-facing topic config. Object IDs are derived from the topic's position
/// in topics[], so users only need to list each topic once.
struct Topic {
  enum class Direction : bool {
    WRITER,
    READER,
  };

  const char* name;
  const char* topic_name;
  const char* type_name;
  const uxrQoS_t qos;
  const Direction dir;

  // These type hooks must match type_name. Use make_topic() so the typed
  // generated functions are adapted to DDSClient's generic void* path.
  const std::size_t message_size;
  const TopicSizeFunc size_of_topic;
  const TopicSerializeFunc serialize_topic;
  const TopicDeserializeFunc deserialize_topic;
};

// Adapts the typed functions generated by microxrceddsgen to the generic
// function pointer shape stored in Topic. New topics should use make_topic()
// instead of hand-writing wrappers for size/serialize/deserialize.
template <
    typename MessageT,
    uint32_t (*SizeOfTopic)(const MessageT* msg, uint32_t size),
    bool (*SerializeTopic)(ucdrBuffer* writer, const MessageT* msg),
    bool (*DeserializeTopic)(ucdrBuffer* reader, MessageT* msg)>
constexpr Topic make_topic(
    const char* name,
    const char* topic_name,
    const char* type_name,
    const Topic::Direction dir,
    const uxrQoS_t qos = DEFAULT_QOS
)
{
  using Adapter = TopicTypeAdapter<MessageT, SizeOfTopic, SerializeTopic, DeserializeTopic>;
  return {
    name,
    topic_name,
    type_name,
    qos,
    dir,
    sizeof(MessageT),
    Adapter::size_of_topic,
    Adapter::serialize_topic,
    Adapter::deserialize_topic,
  };
}

// This is the only list users should normally edit when adding DDS topics.
// The generated functions passed to make_topic() must match the DDS type_name.
constexpr Topic topics[] = {
  make_topic<
      sensor_msgs_msg_Imu,
      sensor_msgs_msg_Imu_size_of_topic,
      sensor_msgs_msg_Imu_serialize_topic,
      sensor_msgs_msg_Imu_deserialize_topic>(
      "IMU", "rt/imu", "sensor_msgs::msg::dds_::Imu_", Topic::Direction::WRITER
  ),
};

constexpr std::size_t topic_count = sizeof(topics) / sizeof(topics[0]);

// Reader callbacks deserialize into a stack buffer sized for the largest
// configured message type. The callback must copy data it wants to keep.
constexpr std::size_t max_topic_message_size()
{
  std::size_t max_size = 0;
  for (const Topic& topic : topics) {
    if (topic.message_size > max_size) {
      max_size = topic.message_size;
    }
  }
  return max_size;
}

// Counts are used to size the create-request/status arrays at compile time.
constexpr std::size_t datawriter_count()
{
  std::size_t count = 0;
  for (const Topic& topic : topics) {
    if (topic.dir == Topic::Direction::WRITER) {
      ++count;
    }
  }
  return count;
}

constexpr std::size_t datareader_count()
{
  std::size_t count = 0;
  for (const Topic& topic : topics) {
    if (topic.dir == Topic::Direction::READER) {
      ++count;
    }
  }
  return count;
}

// XRCE object keys are deterministic: topic at index 0 gets key 1, index 1
// gets key 2, etc. Object type keeps Topic/DataWriter/DataReader IDs separate.
constexpr uint16_t object_key(const std::size_t topic_index)
{
  return static_cast<uint16_t>(topic_index + 1);
}

inline uxrObjectId topic_id(const std::size_t topic_index)
{
  return uxr_object_id(object_key(topic_index), UXR_TOPIC_ID);
}

inline uxrObjectId datawriter_id(const std::size_t topic_index)
{
  return uxr_object_id(object_key(topic_index), UXR_DATAWRITER_ID);
}

inline uxrObjectId datareader_id(const std::size_t topic_index)
{
  return uxr_object_id(object_key(topic_index), UXR_DATAREADER_ID);
}
