<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>uav</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="ubuntu@todo.todo">ubuntu</maintainer>
  <license>TODO: License declaration</license>

  <depend>cv_bridge</depend>
  <depend>python3-opencv</depend>
  <depend>rclpy</depend>
  <depend>px4_msgs</depend>
  <!-- <exec_depend>payload_controller</exec_depend> -->
  <depend>payload_interfaces</depend>
  <depend>sensor_msgs</depend>
  <depend>vehicle_common</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>launch_testing</test_depend>
  <test_depend>tools</test_depend>
  <depend>uav_interfaces</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
