world:
  node: sae_world_node
  name: sae

  physics:
    friction: 0.6

  config:
    template_world: template.sdf

  entities:
    - name: dlz
      model: dlz
      position: [0.0, 0.0, -0.1]
      rpy: [0.0, 0.0, 0.0]

  controllables:
    - name: payload_0
      model: payload
      position: [5.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]

    - name: payload_1
      model: payload
      position: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
