[project]
name = "monorepo"
version = "0.1.0"
dependencies = [ # these should be packages that AREN'T already installed system wide via apt by rosdep to avoid conflicts
    "pydantic>=2.0,<3",
    "apriltag",
    "junitparser"
]

[tool.ruff]
exclude = [
    "controls/sae_2025_ws/src/ros_gz",
    "controls/sae_2025_ws/src/actuator_msgs",
    "controls/sae_2025_ws/src/px4_msgs",
    "PX4-Autopilot",
    "gz-models",
]
