name: 🐛 Bug Report
description: Report something that's broken or not working as expected
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Minor
        - Medium
        - Major
        - Critical
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What's happening, and what did you expect instead?
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
    validations:
      required: false
  - type: textarea
    id: next-steps
    attributes:
      label: Suggested first steps
    validations:
      required: false
