# Simulation Configuration
world:
  name: in_house
  node: hoop_course

  physics:
    friction: 0.0

  config: # world node specific config
    course: ascent
    dlz: [10, 5, 0]
    uav: [0, 0, 0]
    num_hoops: 2
    height: 5
    max_dist: 1
    template_world: template.sdf

  controllables:
    - name: uav_0
      model: x500_mono_cam
      position: [0, 0, 0]
      rpy: [0.0, 0.0, 0.0]

# Scoring parameters
# scoring:
#   name: HoopScore
#   params:
#     vehicle_name: uav_0     # ROS identity whose PX4 state the scorer should track
#     hoop_tolerance: 1.5       # meters - Distance tolerance for hoop passage
#     landing_bonus: 5.0        # Points awarded for landing bonus
#     landing_tolerance: 2.0    # meters - Distance tolerance for landing
#     landing_altitude_max: 0.4 # meters - Maximum altitude to be considered "landed"
