world:
  name: SAEWorldNode
  params:
    template_world: "src/sim/sim/world_gen/worlds/template.sdf"   # Gazebo world template
    physics:
      friction: 0.0 # friction coefficient for the ground plane
    entities:
      - name: "dlz"
        path_to_sdf: "~/.simulation-gazebo/models/dlz/model.sdf"
        position: [20.0, -20.0, 0.0]
        rpy: [0.0, 0.0, 0.0]