#!/usr/bin/env bash


# list of submodules that we manage ourselves and are subject to frequent updates
MANAGED_SUBMODULES=(
    "${PENNAIR_DEPENDENCIES_PATH}"
    "${PENNAIR_PX4_PATH}"
    "${PENNAIR_GZ_MODELS_PATH}"
)

# list of apt packages that AREN'T already installed via rosdep to avoid conflicts (similar to pyproject.toml dependencies)
APT_PACKAGES=(
    "libgflags-dev"
    "openjdk-17-jdk" # for assembling microxrceddsgen in Dependencies
)

# list of npm packages to globally install
GLOBAL_NPM=(
    "xunit-viewer"
)
