#!/usr/bin/env bash


# list of submodules that we manage ourselves and are subject to frequent updates
MANAGED_SUBMODULES=(
    "${PENNAIR_DEPENDENCIES_PATH}"
    "${PENNAIR_PX4_PATH}"
    "${PENNAIR_GZ_MODELS_PATH}"
)
