name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment to prevent conflicts
concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages Metadata
        uses: actions/configure-pages@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install Dependencies
        run: |
          uv pip install -r sphinx/docs-requirements.txt
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Build docs
        run: |
          cd sphinx
          uv run make html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'sphinx/build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
