name: Merge Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

concurrency:
  group: mergebuild-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect_changes:
    name: Detect Changes
    runs-on: ubuntu-latest

    outputs:
      ros_ws: ${{ steps.filter.outputs.ros_ws }}
      # payload_controller: ${{ steps.filter.outputs.payload_controller }}
      # gcs: ${{ steps.filter.outputs.gcs }}
      # docs: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # don't checkout submodules

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: | # TODO: add docs, payload_controller, and gcs
            ros_ws:
              - 'controls/sae_2025_ws/**'

  validate_ros_workspace:
    name: Validate ROS Workspace
    needs: detect_changes
    runs-on: ubuntu-latest
    if: needs.detect_changes.outputs.ros_ws == 'true'

    container:
      image: ghcr.io/pennaerial/monorepo:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout PR
        working-directory: /root/monorepo
        run: |
          git fetch origin "${{ github.sha }}"
          git checkout "${{ github.sha }}"
          bash ci/update_submodules.sh

      - name: Quick Install Dependencies
        run: |
          "$PENNAIR_MONOREPO_PATH/ci/install_deps.sh" --quick

      - name: Build ROS Packages
        run: |
          "$PENNAIR_SAE_WS_PATH/scripts/ci/build_ros.sh" --quick

      - name: Run Unit Tests
        shell: bash
        run: |
          # shellcheck disable=SC1090
          source "/opt/ros/$ROS_DISTRO/setup.bash"
          source "$PENNAIR_SAE_WS_PATH/install/setup.bash"
          source "$PENNAIR_SAE_WS_PATH/.aliasrc" # imports the bash testing functions
          cd "$PENNAIR_SAE_WS_PATH"
          ct

  merge_build_status:
    name: Workflow Status
    needs: # depend on each additional job here
      - validate_ros_workspace
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Check validation results
        env:
          ROS_WS_RESULT: ${{ needs.validate_ros_workspace.result }}
        run: |
          echo "Validation results:"
          echo "  ROS Workspace: $ROS_WS_RESULT"

          if [[ "$ROS_WS_RESULT" != "success" && "$ROS_WS_RESULT" != "skipped" ]]; then
            echo "::error::ROS Workspace validation failed ($ROS_WS_RESULT)"
            exit 1
          fi

          echo "All applicable validations passed."




