name: Static Checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: static-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter paths # if no filter paths have been changed, check passes after this step
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**/*.py'
              - 'pyproject.toml'
            workflows:
              - '.github/workflows/**'
            cpp:
              - '**/*.cpp'
              - '**/*.cc'
              - '**/*.h'
              - '**/*.hpp'
              - '**/*.hh'

      - name: Install Ruff
        if: ${{ steps.filter.outputs.python == 'true' }}
        uses: astral-sh/ruff-action@v4.0.0
        with:
          version: "0.15.10"
          args: "--version"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ruff format & lint
        if: ${{ steps.filter.outputs.python == 'true' }}
        run: |
          ruff format --check --diff .
          ruff check .

      - name: Check workflow files
        if: ${{ steps.filter.outputs.workflows == 'true' }}
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash

      - name: Install Clang tools
        if: ${{ steps.filter.outputs.cpp == 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Run Clang Format
        if: ${{ steps.filter.outputs.cpp == 'true' }}
        run: |
          source dev_env.sh
          source "$PENNAIR_SAE_WS_PATH/.aliasrc" # imports the bash testing functions
          cppfmt --check
